- .travis.yml
- Add config for Travis CI and and Heroku deployment
> Travis CI setup

- app/models/trip.rb
- app/models/user.rb
- db/migrate/20191020213932_create_trips.rb
- db/schema.rb
- spec/factories/trips.rb
- spec/models/trip_spec.rb
- spec/models/user_spec.rb
- Created Trip model/migration
- Created test for Trip model and it's validations/associations
- Added `has_many :trips` association to User model
closes #8
> Create trip model

- app/controllers/api/v1/users_controller.rb
- app/controllers/application_controller.rb
- config/routes.rb
- spec/api/v1/requests/profile_request_spec.rb
- spec/factories/users.rb
- spec/rails_helper.rb
Set up API/V1 namespacing
Added current_user (hardcoded to User where ID ==1)
Added factory bot to rails_helper
Added endpoints for viewing and editing user profile
Does NOT implement GraphQL yet!
> Build API endpoints for GET and PATCH user profile

- app/controllers/api/v1/users_controller.rb
- config/routes.rb
- spec/api/v1/requests/profile_request_spec.rb
Add route, test and action to create a user profile
> Create user profile endpoint

- Gemfile
- Gemfile.lock
- app/controllers/graphql_controller.rb
- app/graphql/mutations/base_mutation.rb
- app/graphql/mutations/create_user.rb
- app/graphql/mutations/update_user.rb
- app/graphql/search_and_rescue_api_schema.rb
- app/graphql/types/base_argument.rb
- app/graphql/types/base_enum.rb
- app/graphql/types/base_field.rb
- app/graphql/types/base_input_object.rb
- app/graphql/types/base_interface.rb
- app/graphql/types/base_object.rb
- app/graphql/types/base_scalar.rb
- app/graphql/types/base_union.rb
- app/graphql/types/mutation_type.rb
- app/graphql/types/query_type.rb
- app/graphql/types/user_type.rb
- config/application.rb
- config/routes.rb
- db/seeds.rb
- spec/factories/users.rb
- spec/graphql/types/mutation_type_spec.rb
- spec/graphql/types/query_type_spec.rb
**WORK IN PROGRESS**
**SOME TESTS FAILING**
- Replace RESTful User routes with GraphQL
> Setup GraphQL User Requests

- app/graphql/mutations/create_vehicle.rb
- app/graphql/mutations/delete_vehicle.rb
- app/graphql/mutations/update_vehicle.rb
- app/graphql/types/mutation_type.rb
- app/graphql/types/query_type.rb
- app/graphql/types/user_type.rb
- app/graphql/types/vehicle_type.rb
- app/models/user.rb
- app/models/vehicle.rb
- db/migrate/20191023212740_create_vehicles.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/vehicles.rb
- spec/graphql/types/mutations/vehicle_mutation_type_spec.rb
- spec/graphql/types/queries/vehicle_query_type_spec.rb
- spec/models/vehicle_spec.rb
- spec/requests/trip_request_spec.rb
- spec/requests/vehicle_request_spec.rb
- Creates queries for user's vehicles and get vehicle by id
- Creates mutations for adding, updating, and removing vehicles (deleteVehicle)
- Implements query, mutation, and request specs for all endpoints
- Create vehicle model and seeds
- Includes model test for vehicle
> Create vehicle queries and mutations in GraphQL 

- app/graphql/mutations/create_user.rb
- app/graphql/mutations/update_user.rb
- app/graphql/types/user_type.rb
- db/migrate/20191024211455_add_height_to_user.rb
- db/schema.rb
- db/seeds.rb
- Create migration for adding height to a user
- Update GraphQL user type with a Height field
- Update seeds to provide a more realistic development view of the database
> Add Height to User 

- app/models/search_and_rescue.rb
- db/csv_data/sar.csv
- db/migrate/20191026182055_create_search_and_rescues.rb
- db/schema.rb
- lib/tasks/import.rake
- spec/factories/search_and_rescues.rb
- spec/models/search_and_rescue_spec.rb
- Create csv file for SAR
- Build rake task to import csv data
- Create model, factory and spec for search and rescue model
> Search and Rescue data import and model setup

- Gemfile
- app/graphql/mutations/add_gear_to_trip.rb
- app/graphql/mutations/remove_gear_from_trip.rb
- app/graphql/types/mutation_type.rb
- app/graphql/types/query_type.rb
- app/graphql/types/trip_gear_type.rb
- app/graphql/types/trip_type.rb
- app/models/gear.rb
- app/models/trip.rb
- app/models/trip_gear.rb
- db/migrate/20191026035829_create_trip_gears.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/gear.rb
- spec/factories/trip_gears.rb
- spec/factories/users.rb
- spec/graphql/types/mutations/trip_gear_mutation_spec.rb
- spec/graphql/types/queries/gear_query_type_spec.rb
- spec/graphql/types/queries/trip_gear_type_spec.rb
- spec/models/gear_spec.rb
- spec/models/trip_gear_spec.rb
- spec/models/trip_spec.rb
- spec/requests/gear_request_spec.rb
- spec/requests/trip_gear_request_spec.rb
- Create migration and model for Trip Gear
- Update seeds
- Create GraphQL and request tests for queries and mutations on TripGear
- Create query and mutations for Trip Gear
- Find all gear associated to a trip
- Add gear and comments to a trip
- Remove gear from a trip
> Trip gear graphql

- app/graphql/types/query_type.rb
- app/graphql/types/search_and_rescue_type.rb
- db/schema.rb
- spec/graphql/types/queries/sar_query_type_spec.rb
- Write query test and create search and rescue query type
> Create queries for Search and Rescue Model

- app/graphql/mutations/create_gear.rb
- app/graphql/mutations/create_trip.rb
- app/graphql/mutations/create_user.rb
- app/graphql/mutations/create_vehicle.rb
- app/graphql/mutations/update_gear.rb
- app/graphql/mutations/update_trip.rb
- app/graphql/mutations/update_user.rb
- app/graphql/mutations/update_vehicle.rb
- app/graphql/types/gear_type.rb
- app/graphql/types/trip_type.rb
- app/graphql/types/user_type.rb
- app/graphql/types/vehicle_type.rb
- db/migrate/20191026194427_replace_age_with_birth_date.rb
- db/migrate/20191026195033_add_description_to_gear.rb
- db/migrate/20191026200222_add_activity_type_to_trip.rb
- db/migrate/20191026202653_add_state_to_vehicle.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/gear.rb
- spec/factories/users.rb
- spec/graphql/types/mutations/gear_mutation_type_spec.rb
- spec/requests/gear_request_spec.rb
Users:
- Replace age with birth_date attribute
Vehicles:
- Add state attribute
Gear:
- Add description attribute
Trips:
- Add activity_type attribute
> Update User, Vehicle, Gear and Trip

- app/graphql/types/user_type.rb
- spec/graphql/types/mutations/user_mutation_type_spec.rb
- Adjust User's experienceLevel field from integer to string
- Update tests to make sure experienceLevel enum is working properly
> Fix experience level

- app/graphql/mutations/end_trip.rb
- app/graphql/types/mutation_type.rb
- app/graphql/types/trip_type.rb
- db/migrate/20191026215624_add_active_to_trip.rb
- db/schema.rb
- spec/graphql/types/mutations/trip_mutation_type_spec.rb
- spec/requests/trip_request_spec.rb
- Add graphql and request tests for endTrip 
- Update Trip to default to `active: true`
- Create mutation for ending a trip
> End trip endpoint

- app/graphql/mutations/add_vehicle_to_trip.rb
- app/graphql/types/mutation_type.rb
- db/migrate/20191028180437_add_vehicle_to_trip.rb
- db/schema.rb
- spec/graphql/types/mutations/trip_mutation_type_spec.rb
- spec/requests/trip_request_spec.rb
- Create migration for adding vehicle_id to Trip
- Create query and request tests for adding a vehicle to a trip
- Create mutation for adding a vehicle to a trip
> Add vehicle to trip endpoint

- .gitignore
- app/graphql/mutations/add_contact_to_trip.rb
- spec/factories/trips.rb
- Adds contact and trip to response of addContactToTrip
> Fix addContactToTrip Response

- .gitignore
- Gemfile
- Gemfile.lock
- app/facades/google_search_facade.rb
- app/graphql/types/trip_type.rb
- app/models/search_and_rescue.rb
- app/services/google_service.rb
- db/csv_data/sar.csv
- db/migrate/20191028223129_add_coordinates_to_sar_teams.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/search_and_rescues.rb
- spec/factories/trips.rb
- spec/fixtures/castle_rock.json
- spec/fixtures/denver.json
- spec/fixtures/google_places_search.json
- spec/fixtures/open_street_map.json
- spec/fixtures/open_street_map_2.json
- spec/fixtures/poncha_springs.json
- spec/graphql/types/queries/nearby_sar_teams_spec.rb
- spec/graphql/types/queries/sar_query_type_spec.rb
- spec/graphql/types/queries/trip_query_type_spec.rb
- spec/models/search_and_rescue_spec.rb
- spec/services/google_service_spec.rb
- spec/spec_helper.rb
- Add gems:
- Faraday
- Webmock
- Geocoder
- Figaro
- Create query test for looking up nearby SAR teams to a trip's starting location
- Create test for Google Place Search service
- Create service/facade for Google Place Search
- Add method to lookup nearby SAR locations with Geocoder gem
**Tests are running slow now, I'll look into this later**
> Nearby SAR Teams

- app/graphql/types/trip_type.rb
- spec/graphql/types/queries/nearby_sar_teams_spec.rb
- Adjust distance to search for nearby SAR teams from 100 miles to 30 miles
> Adjust Distance - Nearby SAR Teams

- app/graphql/mutations/remove_trip.rb
- app/graphql/types/mutation_type.rb
- app/models/trip.rb
- app/models/user.rb
- spec/graphql/types/mutations/trip_mutation_type_spec.rb
- spec/requests/trip_request_spec.rb
- Add tests for removing a trip from the database
- Add mutation for removing a trip from the database
> Add trip remove endpoint

- README.md
- app/models/trip.rb
- Adds sinatra microservice to the readme
- Adds dependent destroy to trip model
> Fix bug for deleting trip mutation

- app/graphql/mutations/update_user.rb
- app/graphql/types/trip_type.rb
- app/graphql/types/user_type.rb
- app/models/trip.rb
- app/models/vehicle.rb
- spec/graphql/types/mutations/gear_mutation_type_spec.rb
- spec/graphql/types/mutations/trip_gear_mutation_spec.rb
- spec/graphql/types/mutations/trip_mutation_type_spec.rb
- spec/requests/contacts_request_spec.rb
- spec/requests/trip_gear_request_spec.rb
- Adds more sad path testing
- Updates trip/vehicle relationship
- Changes height to string in user type and user mutations
> Sad path testing and trip vehicle fix

- app/graphql/mutations/update_user.rb
- app/graphql/types/trip_type.rb
- app/graphql/types/user_type.rb
- Fixes trip vehicle (maybe?)
- Changes height to string on user type and mutation
> Fix trip vehicle

- app/graphql/types/trip_type.rb
> Add conditional for trip vehicle

- app/facades/google_search_facade.rb
- app/graphql/types/trip_type.rb
- Add conditionals to only return if there are nearby SAR teams
> Fix nearby SAR trips

- db/seeds.rb
- Add seed for a 'real' user on a 'real' trip
> Create seed for a real trip

- Gemfile
- Gemfile.lock
- app/graphql/mutations/create_user.rb
- app/models/user.rb
- spec/graphql/types/mutations/user_mutation_type_spec.rb
- spec/requests/profile_request_spec.rb
- Setup bcrypt on User model
- Update CreateUser mutation
- Update tests to reflect changes to requiring a password for user creation
> Setup authentication user model

- app/controllers/application_controller.rb
- app/controllers/graphql_controller.rb
- app/graphql/mutations/sign_in_user.rb
- app/graphql/types/mutation_type.rb
- spec/graphql/types/mutations/sign_in_mutation_type_spec.rb
- spec/requests/gear_request_spec.rb
- spec/requests/profile_request_spec.rb
- spec/requests/sign_in_request_spec.rb
- spec/requests/trip_request_spec.rb
- spec/requests/vehicle_request_spec.rb
- Create mutation and request tests for signing in and expecting the user and unique login token to be returned
- Create a mutation for logging in and returning a unique token
- Adjust GraphqlController to store a session and current user into context
- Add `current_user` method to lookup user with a decrypted token
- Adjust tests to use the new `current_user` method
> Add Sign In Mutation
